/**
 *  © Copyright  2009 Sterling Commerce, Inc.
 */
/*
 * Created on Oct 16,2006
 *
 */
package com.kohls.ibm.ocf.pca.tasks.printpackslip.wizards;

import org.eclipse.swt.SWT;
import org.eclipse.swt.widgets.Composite;
import org.w3c.dom.Element;

import com.kohls.ibm.ocf.pca.tasks.packshipment.wizardpages.KOHLSPackShipmentPage;
import com.kohls.ibm.ocf.pca.tasks.printpackslip.wizardpages.KOHLSPrintPackSlip;
import com.yantra.yfc.rcp.IYRCComposite;
import com.yantra.yfc.rcp.YRCWizardBehavior;

/**
 * @author kiran
 * 
 * Generated by Sterling RCP Tools
 */

public class KOHLSPrintPackSlipWizardBehavior extends YRCWizardBehavior {

	public KOHLSPrintPackSlipWizardBehavior(Composite ownerComposite, String formId,
			Object wizardInput) {

		super(ownerComposite, formId, wizardInput);
		this.wizardInput = wizardInput;
		init();
	}

	/**
	 * Constructor for the behavior class.
	 * 
	 * @param wizardInput
	 */

	private KOHLSPrintPackSlipWizard ownerComposite;

	private Object wizardInput;

	private String currentCustomerMessage;

	private String csrMessage;

	/**
	 * This method initializes the behavior class.
	 */
	public void init() {
	}

	public void setTaskComplete(boolean isTaskComplete) {
	}

	public IYRCComposite createPage(String pageIdToBeShown,
			Composite ownerComposite) {



		/*if (pageIdToBeShown
				.equals(KOHLSPrintPackSlipPage.FORM_ID)) {
			KOHLSPrintPackSlipPage page = new KOHLSPrintPackSlipPage(ownerComposite,SWT.NONE, wizardInput);
			page.setWizBehavior(this);
			return page;
		}*/
		
		if (pageIdToBeShown
				.equals(KOHLSPrintPackSlip.FORM_ID)) {
			KOHLSPrintPackSlip page = new KOHLSPrintPackSlip(ownerComposite,SWT.NONE);
			return page;
		}

		return null;
	}

	public void pageBeingDisposed(String arg0) {

	}

	public boolean canMoveToNextEditor() {
		return false;
	}

	public boolean canPerformNextTask(Element elemTask) {
		return false;
	}

	public String[] getAssociatedTaskCategories() {
		return null;
	}

	public Element getInputForTask(String categoryId, String taskId) {
		return null;
	}

	public String getCustomerName() {
		return null;
	}

	

	public KOHLSPrintPackSlipWizard getOwnerComposite() {
		return ownerComposite;
	}

	public String getCustomerMessage() {
		return currentCustomerMessage;
	}

	public String getStatusMessage() {
		return csrMessage;
	}

	public void setCurrentCustomerMessage(String customerMessage) {
		this.currentCustomerMessage = customerMessage;
	}

	public void setCurrentCsrMessage(String csrMessage) {
		this.csrMessage = csrMessage;
	}

	public boolean checkDirtyBeforeClose() {
		// TODO Auto-generated method stub
		return false;
	}


}
