/**
 *  © Copyright  2009 Sterling Commerce, Inc.
 */
/*
 * Created on Oct 16,2006
 *
 */
package com.kohls.ibm.ocf.pca.tasks.packshipment.wizards;

import org.eclipse.swt.widgets.Composite;

import com.yantra.yfc.rcp.IYRCPanelHolder;
import com.yantra.yfc.rcp.YRCEditorInput;
import com.yantra.yfc.rcp.YRCWizard;
import com.yantra.yfc.rcp.YRCWizardBehavior;

/**
 * @author admin
 * 
 * Generated by Sterling RCP Tools Copyright © 2005, 2009 Sterling Commerce,
 * Inc. All Rights Reserved.
 */

public class KOHLSPackShipmentWizard extends YRCWizard {
	
	public static final String FORM_ID = "com.kohls.ibm.ocf.pca.tasks.packshipment.wizards.KOHLSPackShipmentWizard"; // @jve:decl-index=0:
	
	Object wizardInput;

	public KOHLSPackShipmentWizard(Composite parent, Object wizardInput,
			int style) {
		super(FORM_ID, parent, wizardInput, style);
		this.wizardInput = wizardInput;
		initializeWizard();
		start();
	}
	
	/**
	 * @param wizardId - This is the formId of the wizard
	 * @param parent -This is the composite on which this wizard will open up
	 * @param style - This is SWT.NONE by default
	 * This is the default constructor of the wizard which initializes and starts the
	 * wizard
	 */
	
	public KOHLSPackShipmentWizard(String wizardId, Composite parent, int style) {
		super(wizardId, parent, style);
		initializeWizard();
        start();
	}


	private KOHLSPackShipmentWizardBehavior myBehavior;

	

	public String getFormId() {
		return FORM_ID;
	}

	protected YRCWizardBehavior createBehavior() {
		myBehavior = new KOHLSPackShipmentWizardBehavior(this, FORM_ID,
				wizardInput);
		return myBehavior;
	}

	protected void addPages(Composite parent) {
	}

	protected String getFirstPageId() {
		return null;
	}

	public IYRCPanelHolder getPanelHolder() {
		return null;
	}


	public KOHLSPackShipmentWizardBehavior getWizardBehavior() {
		return myBehavior;
	}

}
