/*
 * Created on May 21,2012
 *
 */
package registry;

import java.util.MissingResourceException;
import java.util.ResourceBundle;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.osgi.framework.BundleContext;

import com.kohls.ibm.ocf.pca.util.KOHLSPCAConstants;
import com.yantra.yfc.rcp.YRCLoginManager;
import com.yantra.yfc.rcp.YRCPlatformUI;

/**
 * @author admin
 *
 * Generated by RCP Tools
 * The main plugin class to be used in the desktop.
 * Copyright © 2005, 2006 Sterling Commerce, Inc. All Rights Reserved.
 */

public class KOHLSPlugin extends AbstractUIPlugin {

	private static KOHLSPlugin plugin;

	public static final String ID = "com.kohls.ibm.ocf.pca";

	/**
	 * The constructor.
	 */
	public KOHLSPlugin() {
		super();
		plugin = this;
		try {
			YRCPlatformUI.registerPlugin(ID, this);
			YRCPlatformUI.registerBundle("com.kohls.ibm.ocf.pca_bundle", ID);
			YRCPlatformUI
					.registerCommands("com.kohls.ibm.ocf.pca_commands", ID);
			YRCPlatformUI.registerTheme("com.kohls.ibm.ocf.pca_theme", ID);
			YRCPlatformUI.registerExtensions("com.kohls.ibm.ocf.pca_extn.yuix",
					ID);
			YRCPlatformUI.registerWizardExtensions("com.kohls.ibm.ocf.pca_recordcustomerpick",ID);
			YRCPlatformUI.registerAboutPluginProperties("about", ID);

			/**
			 * REMOVE THIS CODE IN PRODUCTION
			 * Read from node and enterprise from *.ini
			 * 
			 */

			YRCPlatformUI.trace("Node from env is: "
					+ System.getProperty(KOHLSPCAConstants.INI_PROPERTY_USER_LOGGED_IN_STORE));
			String node = System.getProperty(KOHLSPCAConstants.INI_PROPERTY_USER_LOGGED_IN_STORE);
			if (node != null && node.trim().length() > 0) {
				YRCLoginManager.setDefaultNodeId(node);
				// YRCLoginManager.setNodeEditable(false);
			}
			YRCPlatformUI.trace("Node from env is: "
					+ System.getProperty(KOHLSPCAConstants.INI_PROPERTY_USER_LOGGED_IN_ENTERPRISE));
			String enterprise = System.getProperty(KOHLSPCAConstants.INI_PROPERTY_USER_LOGGED_IN_ENTERPRISE);
			if (enterprise != null && enterprise.trim().length() > 0) {
				YRCLoginManager.setDefaultEnterprise(enterprise);
				// YRCLoginManager.setEnterpriseEditable(false);
			}
			/**
			 * End 
			 */

		} catch (MissingResourceException x) {
			x.printStackTrace();
		}
	}

	/**
	 * This method is called upon plug-in activation
	 */
	public void start(BundleContext context) throws Exception {
		super.start(context);
	}

	/**
	 * This method is called when the plug-in is stopped
	 */
	public void stop(BundleContext context) throws Exception {
		super.stop(context);
	}

	/**
	 * Returns the shared instance.
	 */
	public static KOHLSPlugin getDefault() {
		return plugin;
	}

	/**
	 * Returns the plugin's resource bundle,
	 */
	public ResourceBundle getResourceBundle() {
		return null;
	}

}
