	
/*
 * Created on May 30,2012
 *
 */
package com.kohls.ibm.ocf.pca.tasks.printpackslip.wizardpages;

import org.eclipse.swt.SWT;
import org.eclipse.swt.events.SelectionEvent;
import org.eclipse.swt.events.SelectionListener;
import org.eclipse.swt.graphics.Color;
import org.eclipse.swt.layout.FillLayout;
import org.eclipse.swt.layout.GridData;
import org.eclipse.swt.layout.GridLayout;
import org.eclipse.swt.widgets.Button;
import org.eclipse.swt.widgets.Combo;
import org.eclipse.swt.widgets.Composite;
import org.eclipse.swt.widgets.Event;
import org.eclipse.swt.widgets.Group;
import org.eclipse.swt.widgets.Label;
import org.eclipse.swt.widgets.Listener;
import org.eclipse.swt.widgets.Text;

import com.kohls.ibm.ocf.pca.rcp.KohlsApplicationInitializer;
import com.kohls.ibm.ocf.pca.tasks.printSingles.wizardpages.KOHLSMassSinglesPrintScreenBehavior;
import com.kohls.ibm.ocf.pca.tasks.printpackslip.actions.KOHLSMassMultisRefreshAction;
import com.kohls.ibm.ocf.pca.tasks.printpackslip.actions.KOHLSPrintPackSlipPrintMultisAction;
import com.kohls.ibm.ocf.pca.tasks.printpackslip.actions.KOHLSPrintPackSlipPrintSinglesAction;
import com.kohls.ibm.ocf.pca.util.KOHLSPCAConstants;
import com.yantra.yfc.rcp.IYRCComposite;
import com.yantra.yfc.rcp.IYRCPanelHolder;
import com.yantra.yfc.rcp.YRCButtonBindingData;
import com.yantra.yfc.rcp.YRCComboBindingData;
import com.yantra.yfc.rcp.YRCConstants;
import com.yantra.yfc.rcp.YRCLabelBindingData;
import com.yantra.yfc.rcp.YRCPlatformUI;
import com.yantra.yfc.rcp.YRCTextBindingData;
import com.yantra.yfc.rcp.YRCWizardBehavior;

/**
 * @author admin
 *
 * Generated by RCP Tools
 * Copyright © 2005, 2006 Sterling Commerce, Inc. All Rights Reserved.
 */

public class KOHLSPrintPackSlip extends Composite implements IYRCComposite {

	private Composite pnlRoot = null;
    private KOHLSPrintPackSlipBehavior myBehavior;
    public static final String FORM_ID = "com.kohls.ibm.ocf.pca.tasks.printpackslip.wizardpages.KOHLSPrintPackSlip";
	private Composite compositePrintMultiPackSlip = null;
	private Group grpMultiSKUPrint = null;
	private Composite cmpMultiShipmentType = null;
	private Composite cmpNoOfTortsPerCart = null;
	private Composite cmpNoOfCarts = null;
	private Composite cmpPrinter = null;
	private Label lblMShipmentType = null;
	private Label lblNoOfTorts = null;
	private Button rdbMRegular = null;
	private Button rdbMGift = null;
	private Button rdbMPriority = null;
	private Label lblTotesPerCart = null;
	private Label lblNoOfCarts = null;
	private Text txtNoOfCarts = null;
	private Combo cmbMPrinterID = null;
	private Button btnPrintMultis = null;
	private YRCWizardBehavior wizBehavior;
	private Label lblMaxNumberOfCarts = null;
	private Group grpAvailableCarts = null;
	private Label filler1 = null;
	private Label lblRegular = null;
	private Label lblAvailRegCarts = null;
	private Label lblGiftWrap = null;
	private Label lblAvailGiftCarts = null;
	private Label lblPriority = null;
	private Label lblAvailPriorityCarts = null;
	private Button btnRefresh = null;
	public KOHLSPrintPackSlip(Composite parent, int style) {
		super(parent, style);
		initialize();
        setBindingForComponents();
        myBehavior = new KOHLSPrintPackSlipBehavior(this, FORM_ID);
        
        //TODO
        //setting title - Looks like product defect. Uncommenting makes screen blank.
        //  YRCContainerTitleManager.getTitleProvider().setTitle(YRCPlatformUI.getString("TITLE_PRINT_PACK_SLIP"));
    
	}
	
	private void initialize() {
		createRootPanel();
		this.setLayout(new FillLayout());
		setSize(new org.eclipse.swt.graphics.Point(844,540));
	}
	
    private void setBindingForComponents() {
        //TODO: set all bindings here
    	
    	//setBindingSinglesPrintPanelComponents();
    	setBindingMultisPrintPanelComponents();
    }
    
    private void setBindingMultisPrintPanelComponents() {
    	
    	//binding for Label
    	
    	YRCLabelBindingData lblTotesPerCartBindingData = new YRCLabelBindingData();
    	lblTotesPerCartBindingData.setSourceBinding("TotesPerCart:Tote/@TotesPerCart");
    	lblTotesPerCartBindingData.setTargetBinding("PrintMultiPackShipment:PrintPackShipment/@TotesPerCart");
    	lblTotesPerCartBindingData.setName("lblTotesPerCart");
    	lblTotesPerCart.setData(YRCConstants.YRC_LABEL_BINDING_DEFINITION,
    			lblTotesPerCartBindingData);
    	lblTotesPerCart.setData(YRCConstants.YRC_CONTROL_NAME,
    			"lblTotesPerCart");
    	lblTotesPerCart.setData(YRCConstants.YRC_CONTROL_CUSTOMTYPE,"DisplayText");
    	
    	//binding for Available Number of carts
    	
    	//Regular
    	
    	YRCLabelBindingData lblAvailRegCartsBindingData = new YRCLabelBindingData();
    	lblAvailRegCartsBindingData.setSourceBinding("AvailableCartsOutput:AvailableCarts/@MultiRegular");
    	//lblAvailRegCartsBindingData.setTargetBinding(":PrintPackShipment/@TotesPerCart");
    	lblAvailRegCartsBindingData.setName("lblAvailRegCarts");
    	lblAvailRegCarts.setData(YRCConstants.YRC_LABEL_BINDING_DEFINITION,
    			lblAvailRegCartsBindingData);
    	lblAvailRegCarts.setData(YRCConstants.YRC_CONTROL_NAME,
    			"lblAvailRegCarts");
    	lblAvailRegCarts.setData(YRCConstants.YRC_CONTROL_CUSTOMTYPE,"DisplayText");
    	
    	//Gift
    	
    	YRCLabelBindingData lblAvailGiftCartsBindingData = new YRCLabelBindingData();
    	lblAvailGiftCartsBindingData.setSourceBinding("AvailableCartsOutput:AvailableCarts/@MultiGift");
    	//lblAvailRegCartsBindingData.setTargetBinding("PrintMultiPackShipment:PrintPackShipment/@TotesPerCart");
    	lblAvailGiftCartsBindingData.setName("lblAvailRegCarts");
    	lblAvailGiftCarts.setData(YRCConstants.YRC_LABEL_BINDING_DEFINITION,
    			lblAvailGiftCartsBindingData);
    	lblAvailGiftCarts.setData(YRCConstants.YRC_CONTROL_NAME,
    			"lblAvailGiftCarts");
    	lblAvailGiftCarts.setData(YRCConstants.YRC_CONTROL_CUSTOMTYPE,"DisplayText");
    	
    	//Priority
    	
    	YRCLabelBindingData lblAvailPriorityCartsBindingData = new YRCLabelBindingData();
    	lblAvailPriorityCartsBindingData.setSourceBinding("AvailableCartsOutput:AvailableCarts/@MultiPriority");
    	//lblAvailRegCartsBindingData.setTargetBinding("PrintMultiPackShipment:PrintPackShipment/@TotesPerCart");
    	lblAvailPriorityCartsBindingData.setName("lblAvailPriorityCarts");
    	lblAvailPriorityCarts.setData(YRCConstants.YRC_LABEL_BINDING_DEFINITION,
    			lblAvailPriorityCartsBindingData);
    	lblAvailPriorityCarts.setData(YRCConstants.YRC_CONTROL_NAME,
    			"lblAvailPriorityCarts");
    	lblAvailPriorityCarts.setData(YRCConstants.YRC_CONTROL_CUSTOMTYPE,"DisplayText");
    	
    
    	
    	//
    	
    	
    	//binding for # of carts
    	
    	YRCLabelBindingData lblNoOfCartsBindingData = new YRCLabelBindingData(); 
    	lblNoOfCartsBindingData.setName("lblNoOfCarts");
        lblNoOfCarts.setText(YRCPlatformUI.getFormattedString(YRCPlatformUI.getString("NoofCartsPerTotesNo"),  new String[]{getNoOfTotes()}));
    	lblNoOfCarts.setData(YRCConstants.YRC_LABEL_BINDING_DEFINITION,
    			lblNoOfCartsBindingData);
    	lblNoOfCarts.setData(YRCConstants.YRC_CONTROL_NAME,
    			"lblNoOfCarts");
    	lblNoOfCarts.setData(YRCConstants.YRC_CONTROL_CUSTOMTYPE,"Label");
    	
    	
 	   //binding for radio buttons
 	   
	    YRCButtonBindingData rdbMRegularBindingData  = new YRCButtonBindingData();
		rdbMRegularBindingData.setName("rdbMRegular");
		rdbMRegularBindingData.setTargetBinding("PrintMultiPackShipment:PrintPackShipment/@ShipmentType");
		rdbMRegularBindingData.setCheckedBinding("Multi_Regular");
		rdbMRegular.setData(YRCConstants.YRC_BUTTON_BINDING_DEFINATION, rdbMRegularBindingData); 
		rdbMRegular.setData(YRCConstants.YRC_CONTROL_NAME,"rdbMRegular");
		rdbMRegular.setSelection(true);
	    
	    YRCButtonBindingData rdbMGiftBindingData  = new YRCButtonBindingData();
	    rdbMGiftBindingData.setName("rdbMGift");
	    rdbMGiftBindingData.setTargetBinding("PrintMultiPackShipment:PrintPackShipment/@ShipmentType");
	    rdbMGiftBindingData.setCheckedBinding("Multi_Gift");
		rdbMGift.setData(YRCConstants.YRC_BUTTON_BINDING_DEFINATION, rdbMGiftBindingData); 
		rdbMGift.setData(YRCConstants.YRC_CONTROL_NAME,"rdbMGift");
		
		 YRCButtonBindingData rdbMPriorityBindingData  = new YRCButtonBindingData();
		 rdbMPriorityBindingData.setName("rdbMPriority");
		 rdbMPriorityBindingData.setTargetBinding("PrintMultiPackShipment:PrintPackShipment/@ShipmentType");
		 rdbMPriorityBindingData.setCheckedBinding("Multi_Priority");
		 rdbMPriority.setData(YRCConstants.YRC_BUTTON_BINDING_DEFINATION, rdbMPriorityBindingData); 
		 rdbMPriority.setData(YRCConstants.YRC_CONTROL_NAME,"rdbMPriority");  
	    
	    
		//binding for # of shipment
	    
		YRCTextBindingData txtNoOfCartsBindingData = new YRCTextBindingData();
		
	    txtNoOfCartsBindingData.setTargetBinding("PrintMultiPackShipment:PrintPackShipment/@TotalCarts");
	    txtNoOfCartsBindingData.setName("txtNoOfCarts");
	    txtNoOfCarts.setData(YRCConstants.YRC_TEXT_BINDING_DEFINATION,txtNoOfCartsBindingData);
	    txtNoOfCarts.setData(YRCConstants.YRC_CONTROL_NAME,"txtNoOfCarts");
	    txtNoOfCarts.setData(YRCConstants.YRC_CONTROL_CUSTOMTYPE,"DisplayText");
	    txtNoOfCartsBindingData.setMandatory(true);
	    txtNoOfCartsBindingData.setDataType("PositiveQuantity");
	    
		
		
		//binding for Multi Printer Combo
		
	 	YRCComboBindingData bdCmbMPrinterID = new YRCComboBindingData();
	 	bdCmbMPrinterID.setName("cmbMPrinterID");
	 	bdCmbMPrinterID.setSourceBinding("getDeviceList:Devices/Device/@DeviceId");
	 	bdCmbMPrinterID.setCodeBinding("DeviceId");
	 	bdCmbMPrinterID.setTargetBinding("PrintMultiPackShipment:PrintPackShipment/@PrinterID");
	 	bdCmbMPrinterID.setListBinding("getDeviceList:Devices/Device");
	 	bdCmbMPrinterID.setDescriptionBinding("@DeviceId");
		cmbMPrinterID.setData(YRCConstants.YRC_COMBO_BINDING_DEFINATION, bdCmbMPrinterID);
		cmbMPrinterID.setData(YRCConstants.YRC_CONTROL_NAME,"cmbMPrinterID");
		
	   
    	//Binding For Buttons
       	
       	YRCButtonBindingData btnMultisPrintBindingData = new YRCButtonBindingData();
        btnMultisPrintBindingData.setActionId(KOHLSPrintPackSlipPrintMultisAction.ACTION_ID);
        btnMultisPrintBindingData.setActionHandlerEnabled(true);
        btnMultisPrintBindingData.setName("btnPrintMultis");        
        btnPrintMultis.setData(YRCConstants.YRC_BUTTON_BINDING_DEFINATION, btnMultisPrintBindingData);
        btnPrintMultis.setText(YRCPlatformUI.getString("btnPrintMultis"));
        
     	YRCButtonBindingData btnRefreshBindingData = new YRCButtonBindingData();
     	btnRefreshBindingData.setActionId(KOHLSMassMultisRefreshAction.ACTION_ID);
     	btnRefreshBindingData.setActionHandlerEnabled(true);
     	btnRefreshBindingData.setName("btnRefresh");        
     	btnRefresh.setData(YRCConstants.YRC_BUTTON_BINDING_DEFINATION, btnRefreshBindingData);
     	btnRefresh.setText(YRCPlatformUI.getString("Refresh"));
              
        	
	}

	
	

	public String getFormId() {
        return FORM_ID;
    }
    
    public Composite getRootPanel() {
        return pnlRoot;
    }
    
    public YRCWizardBehavior getWizardBehavior() {
		return this.wizBehavior;
	}

	public void setWizBehavior(YRCWizardBehavior wizBehavior) {
		this.wizBehavior = wizBehavior;
	}

	public KOHLSPrintPackSlipBehavior getWizardPageBehavior() {
		return myBehavior;
	}

	private void createRootPanel() {
		pnlRoot = new Composite(this, SWT.NONE);
	    pnlRoot.setData(YRCConstants.YRC_CONTROL_CUSTOMTYPE,"TaskComposite");
        pnlRoot.setData(YRCConstants.YRC_CONTROL_NAME, "pnlRoot");
        pnlRoot.setLayout(new GridLayout());
        createCompositePrintMultiPackSlip();
	}
	
	public IYRCPanelHolder getPanelHolder() {
        // TODO Complete getPanelHolder
        return null;
    }
    
    public String getHelpId() {
		// TODO Complete getHelpId
		return null;
	}

	/**
	 * This method initializes compositePrintMultiPackSlip	
	 *
	 */
	private void createCompositePrintMultiPackSlip() {
		GridData gridData1 = new GridData();
		gridData1.heightHint = 300;
		gridData1.horizontalAlignment = GridData.FILL;
		gridData1.verticalAlignment = GridData.CENTER;
		gridData1.grabExcessHorizontalSpace = true;
		compositePrintMultiPackSlip = new Composite(getRootPanel(), SWT.NONE);
		compositePrintMultiPackSlip.setData(YRCConstants.YRC_CONTROL_CUSTOMTYPE,"Composite");
		compositePrintMultiPackSlip.setData(YRCConstants.YRC_CONTROL_NAME, "compositePrintMultiPackSlip");
		compositePrintMultiPackSlip.setLayout(new GridLayout());
		createGrpMultiSKUPrint();
		compositePrintMultiPackSlip.setLayoutData(gridData1);
	}

	/**
	 * This method initializes grpMultiSKUPrint	
	 *
	 */
	private void createGrpMultiSKUPrint() {
		GridLayout gridLayout6 = new GridLayout();
		gridLayout6.numColumns = 4;
		gridLayout6.makeColumnsEqualWidth = true;
		GridData gridData4 = new GridData();
		gridData4.horizontalAlignment = GridData.FILL;
		gridData4.grabExcessHorizontalSpace = true;
		gridData4.grabExcessVerticalSpace = true;
		gridData4.verticalSpan = 4;
		gridData4.verticalAlignment = GridData.FILL;
		grpMultiSKUPrint = new Group(compositePrintMultiPackSlip, SWT.NONE);
		grpMultiSKUPrint.setData(YRCConstants.YRC_CONTROL_CUSTOMTYPE, "HeaderLabel");
		grpMultiSKUPrint.setData(YRCConstants.YRC_CONTROL_NAME, "grpMultiSKUPrint");
		grpMultiSKUPrint.setText(YRCPlatformUI.getString("MultiPrintTitle"));
		grpMultiSKUPrint.setLayout(gridLayout6);
		createCmpMultiShipmentType();
		grpMultiSKUPrint.setLayoutData(gridData4);
		createCmpNoOfTortsPerCart();
		createCmpNoOfCarts();
		createCmpPrinter();
	}

	/**
	 * This method initializes cmpMultiShipmentType	
	 *
	 */
	private void createCmpMultiShipmentType() {
		GridData gridData3 = new GridData();
		gridData3.heightHint = -1;
		gridData3.horizontalAlignment = GridData.FILL;
		gridData3.verticalAlignment = GridData.CENTER;
		gridData3.grabExcessHorizontalSpace = true;
		GridData gridData25 = new GridData();
		gridData25.heightHint = 30;
		gridData25.horizontalAlignment = GridData.FILL;
		gridData25.verticalAlignment = GridData.CENTER;
		gridData25.grabExcessHorizontalSpace = true;
		GridData gridData24 = new GridData();
		gridData24.heightHint = 25;
		GridData gridData23 = new GridData();
		gridData23.heightHint = 25;
		GridLayout gridLayout7 = new GridLayout();
		gridLayout7.horizontalSpacing = 0;
		gridLayout7.marginHeight = 8;
		gridLayout7.verticalSpacing = 0;
		GridData gridData22 = new GridData();
		gridData22.horizontalAlignment = GridData.BEGINNING;
		gridData22.grabExcessHorizontalSpace = true;
		gridData22.grabExcessVerticalSpace = false;
		gridData22.heightHint = 25;
		gridData22.verticalAlignment = GridData.FILL;
		GridData gridData18 = new GridData();
		gridData18.horizontalAlignment = GridData.FILL;
		gridData18.grabExcessHorizontalSpace = true;
		gridData18.grabExcessVerticalSpace = true;
		gridData18.verticalAlignment = GridData.FILL;
		cmpMultiShipmentType = new Composite(grpMultiSKUPrint, SWT.NONE);
		cmpMultiShipmentType.setLayoutData(gridData18);
		cmpMultiShipmentType.setLayout(gridLayout7);
		lblMShipmentType = new Label(cmpMultiShipmentType, SWT.NONE);
		lblMShipmentType.setText(YRCPlatformUI.getString("ShipmentType"));
		lblMShipmentType.setLayoutData(gridData22);
		rdbMRegular = new Button(cmpMultiShipmentType, SWT.RADIO);
		rdbMRegular.setText(YRCPlatformUI.getString("Regular"));
		rdbMRegular.setLayoutData(gridData23);
		rdbMGift = new Button(cmpMultiShipmentType, SWT.RADIO);
		rdbMGift.setText(YRCPlatformUI.getString("Gift Wrap"));
		rdbMGift.setLayoutData(gridData24);
		rdbMPriority = new Button(cmpMultiShipmentType, SWT.RADIO);
		rdbMPriority.setText(YRCPlatformUI.getString("Priority"));
		rdbMPriority.setLayoutData(gridData25);
		filler1 = new Label(cmpMultiShipmentType, SWT.NONE);
		filler1.setText("");
		filler1.setLayoutData(gridData3);
		createGrpAvailableCarts();
	}

	/**
	 * This method initializes cmpNoOfTortsPerCart	
	 *
	 */
	private void createCmpNoOfTortsPerCart() {
		GridData gridData27 = new GridData();
		gridData27.heightHint = 25;
		GridLayout gridLayout8 = new GridLayout();
		gridLayout8.marginHeight = 8;
		gridLayout8.verticalSpacing = 0;
		gridLayout8.horizontalSpacing = 0;
		GridData gridData19 = new GridData();
		gridData19.horizontalAlignment = GridData.FILL;
		gridData19.grabExcessVerticalSpace = true;
		gridData19.grabExcessHorizontalSpace = true;
		gridData19.verticalAlignment = GridData.FILL;
		cmpNoOfTortsPerCart = new Composite(grpMultiSKUPrint, SWT.NONE);
		cmpNoOfTortsPerCart.setLayoutData(gridData19);
		cmpNoOfTortsPerCart.setLayout(gridLayout8);
		lblNoOfTorts = new Label(cmpNoOfTortsPerCart, SWT.NONE);
		lblNoOfTorts.setText(YRCPlatformUI.getString("NoOfTotesPerCart"));
		lblNoOfTorts.setLayoutData(gridData27);
		lblTotesPerCart = new Label(cmpNoOfTortsPerCart, SWT.NONE);
	
		
	}

	/**
	 * This method initializes cmpNoOfCarts	
	 *
	 */
	private void createCmpNoOfCarts() {
		GridData gridData31 = new GridData();
		gridData31.horizontalAlignment = GridData.FILL;
		gridData31.grabExcessVerticalSpace = true;
		gridData31.grabExcessHorizontalSpace = true;
		gridData31.verticalAlignment = GridData.END;
		GridData gridData28 = new GridData();
		gridData28.grabExcessHorizontalSpace = true;
		gridData28.heightHint = 25;
		gridData28.horizontalAlignment = GridData.BEGINNING;
		gridData28.verticalAlignment = GridData.FILL;
		gridData28.grabExcessVerticalSpace = false;
		GridLayout gridLayout9 = new GridLayout();
		gridLayout9.horizontalSpacing = 0;
		gridLayout9.marginHeight = 8;
		gridLayout9.marginWidth = 5;
		gridLayout9.verticalSpacing = 0;
		GridData gridData20 = new GridData();
		gridData20.grabExcessHorizontalSpace = true;
		gridData20.verticalAlignment = GridData.FILL;
		gridData20.heightHint = 25;
		gridData20.horizontalAlignment = GridData.FILL;
		cmpNoOfCarts = new Composite(grpMultiSKUPrint, SWT.NONE);
		cmpNoOfCarts.setLayoutData(gridData20);
		cmpNoOfCarts.setLayout(gridLayout9);
		lblNoOfCarts = new Label(cmpNoOfCarts, SWT.NONE);
		lblNoOfCarts.setText("# of Carts");
		lblNoOfCarts.setLayoutData(gridData28);
		txtNoOfCarts = new Text(cmpNoOfCarts, SWT.BORDER);
		lblMaxNumberOfCarts = new Label(cmpNoOfCarts, SWT.NONE|SWT.WRAP);
		lblMaxNumberOfCarts.setLayoutData(gridData31);
		
		lblMaxNumberOfCarts.setText(YRCPlatformUI.getFormattedString
				(YRCPlatformUI.getString("LBL_MAX_NUMBER_OF_CARTS"),new String[]{YRCPlatformUI.getString("MAX_NUMBER_OF_CARTS")}));
	}

	/**
	 * This method initializes cmpPrinter	
	 *
	 */
	private void createCmpPrinter() {
		GridData gridData30 = new GridData();
		gridData30.horizontalAlignment = GridData.CENTER;
		gridData30.grabExcessVerticalSpace = true;
		gridData30.heightHint = 30;
		gridData30.widthHint = 130;
		gridData30.verticalAlignment = GridData.END;
		GridLayout gridLayout10 = new GridLayout();
		gridLayout10.horizontalSpacing = 0;
		gridLayout10.marginHeight = 8;
		gridLayout10.verticalSpacing = 0;
		GridData gridData21 = new GridData();
		gridData21.grabExcessHorizontalSpace = true;
		gridData21.verticalAlignment = GridData.FILL;
		gridData21.grabExcessVerticalSpace = true;
		gridData21.horizontalAlignment = GridData.BEGINNING;
		cmpPrinter = new Composite(grpMultiSKUPrint, SWT.NONE);
		createCmbMPrinterID();
		cmpPrinter.setLayout(gridLayout10);
		cmpPrinter.setLayoutData(gridData21);
		btnPrintMultis = new Button(cmpPrinter, SWT.NONE);
		btnPrintMultis.setText(YRCPlatformUI.getString("PrintMultis"));
		btnPrintMultis.setLayoutData(gridData30);
	}

	/**
	 * This method initializes cmbMPrinterID	
	 *
	 */
	private void createCmbMPrinterID() {
		GridData gridData29 = new GridData();
		gridData29.horizontalAlignment = GridData.FILL;
		gridData29.grabExcessHorizontalSpace = true;
		gridData29.grabExcessVerticalSpace = false;
		gridData29.heightHint = 50;
		gridData29.verticalAlignment = GridData.BEGINNING;
		cmbMPrinterID = new Combo(cmpPrinter, SWT.READ_ONLY);
		cmbMPrinterID.setLayoutData(gridData29);
		cmbMPrinterID.setText("Printer ID");
		cmbMPrinterID.addSelectionListener(new SelectionListener(){
			public void widgetSelected(SelectionEvent e) {
		        myBehavior.handleComboBoxSelection(cmbMPrinterID);
		    }
			public void widgetDefaultSelected(SelectionEvent e) {
		      
		    }
		});
	}
	
	
	public String getNoOfTotes() {
		String strTotes="";
		
//		if(!YRCPlatformUI.isVoid(System.getProperty(KOHLSPCAConstants.INI_PROPERTY_TOTES))){
//				strTotes= System.getProperty(KOHLSPCAConstants.INI_PROPERTY_TOTES);
//		}
		strTotes = KohlsApplicationInitializer.getTerminalPropertyForUISession(KOHLSPCAConstants.INI_SHIPMENT_PER_TOTES);
	     return strTotes;
	}

	/**
	 * This method initializes grpAvailableCarts	
	 *
	 */
	private void createGrpAvailableCarts() {
		GridData gridData7 = new GridData();
		gridData7.horizontalAlignment = GridData.BEGINNING;
		gridData7.verticalAlignment = GridData.CENTER;
		GridData gridData6 = new GridData();
		gridData6.horizontalAlignment = GridData.BEGINNING;
		gridData6.grabExcessHorizontalSpace = false;
		gridData6.grabExcessVerticalSpace = true;
		gridData6.verticalAlignment = GridData.CENTER;
		GridData gridData5 = new GridData();
		gridData5.horizontalAlignment = GridData.BEGINNING;
		gridData5.verticalAlignment = GridData.CENTER;
		GridData gridData32 = new GridData();
		gridData32.horizontalAlignment = GridData.CENTER;
		gridData32.grabExcessHorizontalSpace = true;
		gridData32.grabExcessVerticalSpace = false;
		gridData32.verticalAlignment = GridData.FILL;
		GridData gridData = new GridData();
		gridData.grabExcessHorizontalSpace = false;
		gridData.horizontalAlignment = GridData.FILL;
		gridData.verticalAlignment = GridData.FILL;
		gridData.grabExcessVerticalSpace = false;
		GridLayout gridLayout = new GridLayout();
		gridLayout.makeColumnsEqualWidth = true;
		gridLayout.marginWidth = 8;
		gridLayout.marginHeight = 8;
		gridLayout.horizontalSpacing = 8;
		gridLayout.verticalSpacing = 8;
		gridLayout.numColumns = 2;
		grpAvailableCarts = new Group(cmpMultiShipmentType, SWT.NONE);
		grpAvailableCarts.setText(YRCPlatformUI.getString("AvailableCartsForShipmentType"));
		grpAvailableCarts.setLayout(gridLayout);
		grpAvailableCarts.setLayoutData(gridData);
		lblRegular = new Label(grpAvailableCarts, SWT.NONE);
		lblRegular.setText("Regular");
		lblRegular.setLayoutData(gridData5);
		lblAvailRegCarts = new Label(grpAvailableCarts, SWT.NONE);
		lblAvailRegCarts.setText("");
		lblGiftWrap = new Label(grpAvailableCarts, SWT.NONE);
		lblGiftWrap.setText("Gift Wrap");
		lblGiftWrap.setLayoutData(gridData6);
		lblAvailGiftCarts = new Label(grpAvailableCarts, SWT.NONE);
		lblAvailGiftCarts.setText("");
		lblPriority = new Label(grpAvailableCarts, SWT.NONE);
		lblPriority.setText("Priority");
		lblPriority.setLayoutData(gridData7);
		lblAvailPriorityCarts = new Label(grpAvailableCarts, SWT.NONE);
		lblAvailPriorityCarts.setText("");
		Label filler4 = new Label(grpAvailableCarts, SWT.NONE);
		btnRefresh = new Button(grpAvailableCarts, SWT.NONE);
		btnRefresh.setText(YRCPlatformUI.getString("Refresh"));
		btnRefresh.setLayoutData(gridData32);
	}
	
	public KOHLSPrintPackSlipBehavior getBehavior() {
        return myBehavior;
    }
  
}
